version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./storage/lib:/var/lib/mypc
      - ./storage/log:/var/log/mypc
      - .:/usr/share/webapps/mypc
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.settings.local
    links:
      - database
      - redis
  database:
    image: postgres:10.3-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=mypc
  redis:
    image: redis:6.2
